VERSION = 2.5
QMAKE_TARGET_COMPANY = Christian Kaiser
QMAKE_TARGET_PRODUCT = Lightscreen
QMAKE_TARGET_DESCRIPTION = Lightscreen Screenshot Tool
QMAKE_TARGET_COPYRIGHT = Copyright (C) 2008-2018 Christian Kaiser

DEFINES += APP_VERSION=\\\"$$VERSION\\\"
